"""Write docs/evaluation/company-coverage.md: how many snapshot companies each name form reaches.

For every operating company in the universe snapshot, ask a question in several
everyday forms of its name ("Danaher Corporation revenue", "Danaher's revenue",
"$DHR revenue", "danaher revenue") and check that the planner's issuer index
finds that company, and only it. No network and no model: the same index the
rules planner reads questions with, and spec resolution reads company fields with.

Usage: uv run python scripts/company_coverage.py
"""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path

from financial_analyst_agent.issuer_index import _core_name
from financial_analyst_agent.ranking import SnapshotRanking
from financial_analyst_agent.rules_planner import issuer_index
from financial_analyst_agent.universe import (
    UniverseCompany,
    is_common_operating_listing,
    load_universe_snapshot,
)

OUT = Path(__file__).resolve().parent.parent / "docs/evaluation/company-coverage.md"
_EXAMPLES = 12


def _spoken(company: UniverseCompany) -> str:
    """The name without its legal form, as it is said: "Danaher", "Home Depot"."""
    core = _core_name(company.name)
    words = company.name.replace(",", " ").split()
    if words and words[0].casefold() == "the":
        words = words[1:]
    # Keep the name's own capitals, word for word, as far as the core goes.
    for end in range(1, len(words) + 1):
        if _core_name(" ".join(words[:end])) == core:
            return " ".join(words[:end])
    return company.name


FORMS: tuple[tuple[str, Callable[[UniverseCompany], str]], ...] = (
    ("Full legal name", lambda c: f"{c.name} revenue"),
    ("Name without legal form", lambda c: f"{_spoken(c)} revenue"),
    ("Possessive", lambda c: f"What was {_spoken(c)}'s revenue?"),
    ("Lower case", lambda c: f"{_spoken(c).lower()} revenue"),
    ("$TICKER", lambda c: f"${c.ticker} revenue"),
    ("In a comparison", lambda c: f"Compare {_spoken(c)} and Walmart revenue"),
)


def main() -> None:
    snapshot = load_universe_snapshot(None)
    index = issuer_index()
    ranking = SnapshotRanking(snapshot, index)
    companies: dict[str, UniverseCompany] = {}
    for company in sorted(snapshot.companies, key=lambda c: c.market_cap, reverse=True):
        if is_common_operating_listing(company):
            companies.setdefault(company.cik, company)

    def cik_of(query: str) -> str | None:
        try:
            return ranking.lookup_member(query).cik
        except Exception:  # noqa: BLE001 - a query that names no member counts as a miss
            return None

    rows: list[tuple[str, int, int, list[str]]] = []
    for label, form in FORMS:
        hits, misses = 0, []
        for company in companies.values():
            question = form(company)
            found = {cik_of(mention.query) for mention in index.find(question)}
            found.discard(None)
            wanted = {company.cik} | ({cik_of("Walmart")} if "Walmart" in question else set())
            if company.cik in found and found <= wanted:
                hits += 1
            else:
                misses.append(f"`{question}`")
        rows.append((label, hits, len(companies), misses))

    lines = [
        "# Company name coverage",
        "",
        f"Every operating company in the universe snapshot ({len(companies):,}, as of "
        f"{snapshot.as_of.isoformat()}), asked about in six everyday forms of its name. A form "
        "counts when the planner's issuer index finds that company and no other. The index is "
        "the one the rules planner reads questions with and spec resolution reads a model "
        "planner's company fields with. Generated by `scripts/company_coverage.py`; no "
        "network or model is involved.",
        "",
        "| Form | Example | Found | Share |",
        "| --- | --- | ---: | ---: |",
    ]
    sample = next(iter(companies.values()))
    for (label, form), (_, hits, total, _misses) in zip(FORMS, rows, strict=True):
        lines.append(f"| {label} | `{form(sample)}` | {hits:,} / {total:,} | {hits / total:.1%} |")
    lines.append("")
    lines.append(
        "What is missed, by design or not yet: a one-word name that is a generic word "
        "(Southern, People, Universal) or two characters (Nu, On, Q2), which a question "
        "almost always means as the word; a name a larger company also goes by (Vertex is "
        "Vertex Pharmaceuticals), or one several companies share, which is asked about; names "
        "with a dot (JD.com, Cars.com); and some long Spanish and Portuguese legal names."
    )
    lines.append("")
    for label, hits, total, misses in rows:
        if misses:
            lines.append(f"<details><summary>{label}: {total - hits} missed</summary>")
            lines.append("")
            lines.append(", ".join(misses[:_EXAMPLES]) + (", …" if len(misses) > _EXAMPLES else ""))
            lines.append("")
            lines.append("</details>")
            lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    for label, hits, total, _ in rows:
        print(f"{label}: {hits}/{total} ({hits / total:.1%})")


if __name__ == "__main__":
    main()
