#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Go-live wizard for the hosted demo (ticket 10; ADR 0006 "Hosting"; docs/deploy.md).
# Run it from anywhere in the repo, on macOS, Linux, or WSL:
#
#   scripts/deploy_wizard.sh           walk through going live, stage by stage
#   scripts/deploy_wizard.sh --check   re-verify the saved deploy, no prompts
#
# It is safe to re-run: the proxy token is kept, and a stage whose result
# already checks out says so and moves on. Values are saved to .env.deploy
# (gitignored), never .env: the API reads .env, and a proxy token there would
# make the local API refuse the local window.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"
ENV_FILE="${DEPLOY_ENV_FILE:-.env.deploy}"

SERVICE_NAME="financial-analyst-api"  # render.yaml services[0].name
WAKE_SECONDS="${WAKE_SECONDS:-180}"   # a sleeping free instance takes about a minute
BUILD_SECONDS="${BUILD_SECONDS:-1200}" # the first Docker build on Render's free plan
SMOKE="scripts/smoke_api_image.py"

usage() {
  cat <<'USAGE'
Usage: scripts/deploy_wizard.sh [--check | --help]

Walks you through putting the hosted demo live (docs/deploy.md), in 8 stages:
  1. Before you start   tools, and the deploy files on master
  2. Proxy token        generate the shared proxy token (kept on re-runs)
  3. Render             create the API from the Blueprint, paste the proxy token
  4. Render Auto-Deploy confirm "After CI Checks Pass", or wire the deploy hook
  5. Vercel             import the repo with Root Directory web
  6. Vercel variables   set API_ORIGIN and API_PROXY_TOKEN, then redeploy
  7. Proxy check        health through the Vercel URL; Render refuses direct calls
  8. Browser check      run the browser check (Playwright) against the hosted window

Values are saved to .env.deploy (gitignored). Re-running skips or re-verifies
stages that are already done.

Options:
  --check     re-run every check against the saved deploy, without prompts;
              exits 1 if any check fails
  -h, --help  show this help

Environment:
  DEPLOY_ENV_FILE  where values are saved (default .env.deploy)
  WAKE_SECONDS     how long to wait for a sleeping API (default 180)
USAGE
}

MODE=wizard
if (( $# > 1 )); then usage >&2; exit 2; fi
case "${1:-}" in
  "") ;;
  --check) MODE=check ;;
  -h|--help) usage; exit 0 ;;
  *) usage >&2; exit 2 ;;
esac

# ── Helpers ───────────────────────────────────────────────────────────────

ok()   { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }
fail() { printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET"; }

# load KEY — set $KEY from ENV_FILE (empty when not saved yet).
load() {
  local value
  value=$(_existing "$1" || true)
  printf -v "$1" '%s' "$value"
}

# normalize_url URL — trim spaces and trailing slashes; add https:// if missing.
normalize_url() {
  local url="$1"
  url="${url#"${url%%[![:space:]]*}"}"
  url="${url%"${url##*[![:space:]]}"}"
  while [[ "$url" == */ ]]; do url="${url%/}"; done
  if [[ -n "$url" && "$url" != http://* && "$url" != https://* ]]; then url="https://$url"; fi
  printf '%s' "$url"
}

# ask_url KEY "Prompt" — ask for an https URL until one is given.
ask_url() {
  local key="$1" prompt="$2" tries=0 value
  while (( tries < 5 )); do
    tries=$((tries + 1))
    ask "$key" "$prompt"
    value=$(normalize_url "${!key}")
    if [[ "$value" == https://* ]]; then
      printf -v "$key" '%s' "$value"
      return 0
    fi
    warn "that isn't an https:// URL; try again"
  done
  fail "no URL given"
  exit 1
}

mask() { printf '%s…%s' "${1:0:4}" "${1: -4}"; }

new_token() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  elif [[ -n "$PYTHON" ]]; then
    "$PYTHON" -c 'import secrets; print(secrets.token_hex(32))'
  else
    od -An -tx1 -N32 /dev/urandom | tr -d ' \n'
  fi
}

# copy_clipboard VALUE — macOS, WSL, Wayland, or X11; fails if none works.
copy_clipboard() {
  local tool
  for tool in pbcopy clip.exe wl-copy; do
    if command -v "$tool" >/dev/null 2>&1 && printf '%s' "$1" | "$tool" >/dev/null 2>&1; then
      return 0
    fi
  done
  if command -v xclip >/dev/null 2>&1 \
    && printf '%s' "$1" | xclip -selection clipboard >/dev/null 2>&1; then
    return 0
  fi
  return 1
}

# hand_over LABEL VALUE [secret] — put a value on the clipboard, ready to paste.
# A public value is also shown; a secret is shown only if you ask.
hand_over() {
  local label="$1" value="$2" secret="${3:-}"
  if copy_clipboard "$value"; then
    printf '  %s⧉ copied%s %s to your clipboard\n' "$GREEN" "$RESET" "$label"
    if [[ -z "$secret" ]]; then note "  $value"; fi
  elif [[ -z "$secret" ]]; then
    say "$label: $value"
  else
    warn "no clipboard tool found (pbcopy, clip.exe, wl-copy, xclip)"
    if confirm "Show $label on screen so you can copy it?"; then say "$value"; fi
  fi
}

PYTHON=""
for candidate in python3 python; do
  if command -v "$candidate" >/dev/null 2>&1 \
    && "$candidate" -c 'import sys; sys.exit(sys.version_info < (3, 8))' >/dev/null 2>&1; then
    PYTHON="$candidate"
    break
  fi
done

# ── Checks, shared by the stages and --check ──────────────────────────────

# status URL — HTTP status of a plain GET (no token), or 000 if nothing answered.
status() {
  local code
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 90 "$1" 2>/dev/null) || true
  printf '%s' "${code:-000}"
}

# healthy BASE — /api/health answers {"status": "ok"}.
healthy() {
  curl -fsS --max-time 90 "$1/api/health" 2>/dev/null | grep -Eq '"status" *: *"ok"'
}

# wait_healthy BASE SECONDS — poll the health check (a free instance may be asleep).
wait_healthy() {
  local base="$1" limit="$2" start=$SECONDS
  if healthy "$base"; then return 0; fi
  printf '  %swaiting up to %ss for %s/api/health' "$DIM" "$limit" "$base"
  while (( SECONDS - start < limit )); do
    sleep 5
    printf '.'
    if healthy "$base"; then printf '%s\n' "$RESET"; return 0; fi
  done
  printf '%s\n' "$RESET"
  return 1
}

# smoke BASE [TOKEN] — take the "Verify a quarterly fact" guided story. The
# token goes in the environment, not on the command line where ps shows it.
# Without one, SMOKE_PROXY_TOKEN is set empty, so a value exported in your shell
# cannot stand in for the one the Vercel proxy should add.
smoke() {
  SMOKE_OUT=$(SMOKE_PROXY_TOKEN="${2:-}" "$PYTHON" "$SMOKE" --base-url "$1" --timeout 180 2>&1)
}

# check LABEL FN — run one check, print ✓ or ✗ with its detail, count failures.
# FN sets DETAIL (shown either way) and HINT (how to fix it, wizard only).
FAILED=0
WAIT_LIMIT="$WAKE_SECONDS"
check() {
  DETAIL=""
  HINT=""
  if "$2"; then
    ok "$1${DETAIL:+ ($DETAIL)}"
    return 0
  fi
  fail "$1${DETAIL:+: $DETAIL}"
  if [[ "$MODE" == wizard && -n "$HINT" ]]; then printf '%s\n' "$HINT" | sed 's/^/    /'; fi
  FAILED=$((FAILED + 1))
  return 1
}

c_render_health() {
  if wait_healthy "$RENDER_API_URL" "$WAIT_LIMIT"; then return 0; fi
  DETAIL="no answer from $RENDER_API_URL/api/health"
  HINT="Render → $SERVICE_NAME → Events (or Logs) shows the build and any error.
The first Docker build takes several minutes; a sleeping service about one."
  return 1
}

c_render_refuses() {
  local code
  code=$(status "$RENDER_API_URL/api/meta")
  if [[ "$code" == 401 ]]; then DETAIL="401"; return 0; fi
  DETAIL="/api/meta answered $code, expected 401"
  HINT="API_PROXY_TOKEN is not set on Render. Render → $SERVICE_NAME → Environment →
API_PROXY_TOKEN → edit → paste the token → Save and deploy (it may read
\"Save, rebuild, and deploy\"). If the variable is missing, Add it."
  return 1
}

c_render_story() {
  if [[ -z "$PYTHON" ]]; then DETAIL="skipped: python3 not found"; return 0; fi
  if smoke "$RENDER_API_URL" "$API_PROXY_TOKEN"; then return 0; fi
  DETAIL="${SMOKE_OUT##*$'\n'}"
  HINT="A 401 here means Render's API_PROXY_TOKEN differs from the one in $ENV_FILE.
Render → $SERVICE_NAME → Environment → API_PROXY_TOKEN → paste it again → Save."
  return 1
}

c_vercel_page() {
  local code
  code=$(status "$VERCEL_URL/")
  if [[ "$code" == 200 ]]; then return 0; fi
  DETAIL="$VERCEL_URL answered $code"
  if [[ "$code" == 401 || "$code" == 403 ]]; then
    HINT="That is Vercel's login wall (Deployment Protection). Use the project's short
production domain from Settings → Domains, not a deployment URL. If that one asks
for a login too: Settings → Deployment Protection → Vercel Authentication, and pick
the option that leaves production public (if you don't see one, turn it off; the
API behind the proxy still needs the token)."
  else
    HINT="Vercel → the project → Deployments shows whether the build finished."
  fi
  return 1
}

c_vercel_health() {
  if wait_healthy "$VERCEL_URL" "$WAIT_LIMIT"; then return 0; fi
  local code
  code=$(status "$VERCEL_URL/api/health")
  DETAIL="$VERCEL_URL/api/health answered $code"
  HINT="502 means the proxy cannot reach API_ORIGIN; 404 means the window is not
deployed at this URL. Check API_ORIGIN is $RENDER_API_URL for Production,
then Deployments → latest → ⋯ → Redeploy: variables reach new deployments only."
  return 1
}

c_vercel_story() {
  if [[ -z "$PYTHON" ]]; then DETAIL="skipped: python3 not found"; return 0; fi
  if smoke "$VERCEL_URL"; then return 0; fi
  DETAIL="${SMOKE_OUT##*$'\n'}"
  HINT="A 401 here means Vercel's API_PROXY_TOKEN is missing or differs from Render's.
Set it for Production and Preview, then Deployments → latest → ⋯ → Redeploy."
  return 1
}

check_render() {
  check "health check on Render" c_render_health \
    && check "Render refuses a call without the token" c_render_refuses \
    && check "guided story on Render with the saved token" c_render_story
}

check_vercel() {
  check "health check through the Vercel proxy" c_vercel_health \
    && check "guided story through the Vercel proxy" c_vercel_story
}

load API_PROXY_TOKEN
load RENDER_API_URL
load VERCEL_URL
load RENDER_AUTO_DEPLOY
load BROWSER_CHECK_PASSED
RENDER_API_URL=$(normalize_url "$RENDER_API_URL")
VERCEL_URL=$(normalize_url "$VERCEL_URL")

# ── --check: re-verify a saved deploy ─────────────────────────────────────

if [[ "$MODE" == check ]]; then
  missing=""
  for key in API_PROXY_TOKEN RENDER_API_URL VERCEL_URL; do
    if [[ -z "${!key}" ]]; then missing="$missing $key"; fi
  done
  if [[ -n "$missing" ]]; then
    fail "$ENV_FILE has no$missing: run scripts/deploy_wizard.sh first"
    exit 1
  fi
  printf '\n%sChecking %s and %s%s\n' "$BOLD" "$RENDER_API_URL" "$VERCEL_URL" "$RESET"
  check_render || true
  check_vercel || true
  if (( FAILED )); then exit 1; fi
  exit 0
fi

if [[ ! -t 0 ]]; then
  printf 'The wizard is interactive: run it in a terminal, or use --check.\n' >&2
  exit 2
fi

REPO_SLUG=$(git remote get-url origin 2>/dev/null || true)
REPO_SLUG="${REPO_SLUG%.git}"
REPO_SLUG="${REPO_SLUG#*github.com[:/]}"
REPO_SLUG="${REPO_SLUG:-bpyman/financial-analyst-agent}"

# ── The stages ────────────────────────────────────────────────────────────

stage_preflight() {
  stage "Before you start"
  say "Checking the tools this wizard uses, and that master has the deploy files."
  if ! command -v curl >/dev/null 2>&1; then fail "curl is missing: install it, then re-run"; exit 1; fi
  ok "curl"
  if [[ -n "$PYTHON" ]]; then
    ok "$PYTHON (takes a guided story through the hosted API)"
  else
    warn "Python 3.8+ not found: the guided-story checks will be skipped"
  fi
  if command -v npm >/dev/null 2>&1; then
    ok "npm (runs the browser check in stage 8)"
  else
    warn "npm not found: install Node 22 (see .nvmrc) for the browser check in stage 8"
  fi
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    ok "gh, signed in (only needed if stage 4 falls back to the deploy hook)"
  else
    note "gh (GitHub CLI) missing or signed out: only needed if stage 4 falls back to"
    note "the deploy hook, and then you can paste the secret on github.com instead."
  fi

  local path missing=""
  if git fetch --quiet origin master >/dev/null 2>&1; then
    for path in render.yaml Dockerfile web/package.json web/vercel.json; do
      git cat-file -e "origin/master:$path" 2>/dev/null || missing="$missing $path"
    done
    if [[ -z "$missing" ]]; then
      ok "master has render.yaml, the Dockerfile, and the web/ window"
    else
      warn "master is missing:$missing"
      say "Render and Vercel build master. Merge the parity PR and the deploy PR first."
      confirm "Continue anyway?" || exit 1
    fi
  else
    warn "couldn't fetch origin/master to check for render.yaml and web/"
  fi

  if command -v render >/dev/null 2>&1; then
    local out
    if out=$(render blueprints validate </dev/null 2>&1); then
      ok "render blueprints validate"
    else
      warn "render blueprints validate did not pass (if it asks you to log in, run render login):"
      printf '%s\n' "$out" | sed 's/^/    /'
      confirm "Continue anyway? Render also validates the Blueprint in stage 3" || exit 1
    fi
  else
    note "Render CLI not installed: Render validates render.yaml when it reads it in stage 3."
  fi
  pause "Press Enter to continue"
}

stage_token() {
  stage "Generate the proxy token"
  say "Render and Vercel share one secret. The Vercel proxy sends it as X-Proxy-Token,"
  say "and the API refuses every call but /api/health that lacks it."
  if [[ -n "$API_PROXY_TOKEN" ]]; then
    ok "keeping the token saved in $ENV_FILE ($(mask "$API_PROXY_TOKEN"))"
    note "Re-runs keep it so Render and Vercel stay in step. To rotate it, delete the"
    note "API_PROXY_TOKEN line from $ENV_FILE, re-run, and paste the new one into both."
  else
    API_PROXY_TOKEN=$(new_token)
    write_env API_PROXY_TOKEN "$API_PROXY_TOKEN"
    ok "generated a 64-character token ($(mask "$API_PROXY_TOKEN"))"
  fi
  note "$ENV_FILE is gitignored. Never commit it or paste the token anywhere else."
  pause "Press Enter to continue"
}

stage_render() {
  stage "Render — create the API from the Blueprint"
  if [[ -n "$RENDER_API_URL" ]]; then
    say "Checking the saved service, $RENDER_API_URL (a sleeping one takes a minute)…"
    if check_render; then
      ok "already live: nothing to do here"
      pause "Press Enter to continue"
      return
    fi
    confirm "Walk through creating the service again?" || { retry_render; return; }
  fi
  open_url "https://dashboard.render.com"
  step "Sign in (GitHub is simplest). Click New (top right) → Blueprint."
  note "If New has no Blueprint entry, open Blueprints in the left sidebar → New Blueprint Instance."
  step "Find $REPO_SLUG and click Connect."
  note "Not listed? Use the Configure / Connect GitHub link to give Render access to the repo."
  step "Blueprint Name: financial-analyst-agent. Branch: master."
  step "Render lists one web service, $SERVICE_NAME (free), and a field for API_PROXY_TOKEN."
  hand_over "the proxy token" "$API_PROXY_TOKEN" secret
  step "Paste it into API_PROXY_TOKEN, then click Deploy Blueprint."
  note "If the button reads Apply, that is the same step. If no token field appears, carry on:"
  note "the check below will show where to add it."
  pause "Press Enter once you've clicked Deploy Blueprint"
  step "Open the $SERVICE_NAME service (Dashboard → Projects/Services). Its URL is under"
  step "the name at the top, like https://$SERVICE_NAME.onrender.com (maybe with a suffix)."
  ask_url RENDER_API_URL "Paste the service URL:"
  if [[ "$RENDER_API_URL" != *.onrender.com ]]; then warn "that isn't an onrender.com URL; using it anyway"; fi
  write_env RENDER_API_URL "$RENDER_API_URL"
  say "The first Docker build takes several minutes; this waits up to $((BUILD_SECONDS / 60)) minutes."
  WAIT_LIMIT=$BUILD_SECONDS
  retry_render
  WAIT_LIMIT=$WAKE_SECONDS
}

# retry_render — re-run the Render checks until they pass or you move on.
retry_render() {
  until check_render; do
    if ! confirm "Fix that, then check again?"; then
      SKIPPED+=("Render checks (re-run scripts/deploy_wizard.sh --check once fixed)")
      return
    fi
  done
  pause "Press Enter to continue"
}

stage_autodeploy() {
  stage "Render — deploy only after CI passes"
  say "render.yaml asks Render to deploy a commit only once its GitHub checks pass"
  say "(autoDeployTrigger: checksPass). Nothing confirmed the free plan offers that."
  if [[ "$RENDER_AUTO_DEPLOY" == checksPass ]]; then
    ok "you confirmed Auto-Deploy reads After CI Checks Pass"
    confirm "Look again?" || return 0
  elif [[ "$RENDER_AUTO_DEPLOY" == hook ]]; then
    ok "you set up the deploy hook fallback"
    confirm "Look again?" || return 0
  fi
  step "Render → $SERVICE_NAME → Settings → Build & Deploy → Auto-Deploy."
  note "If there is no Build & Deploy heading, scroll Settings for the Auto-Deploy field."
  say ""
  say "What does Auto-Deploy say?"
  say "  1) After CI Checks Pass"
  say "  2) something else, and After CI Checks Pass is not among its options"
  local choice=""
  while [[ "$choice" != 1 && "$choice" != 2 ]]; do
    printf '  %sEnter 1 or 2:%s ' "$BOLD" "$RESET"
    read -r choice || exit 1
  done
  if [[ "$choice" == 1 ]]; then
    write_env RENDER_AUTO_DEPLOY checksPass
    ok "Render deploys a commit once CI passes; CI's deploy-api job stays dormant"
    pause "Press Enter to continue"
    return
  fi
  say "Fallback: CI deploys through Render's deploy hook once every job passes."
  step "Same Settings page → Deploy Hook → copy the URL"
  note "(it looks like https://api.render.com/deploy/srv-…?key=…; keep it secret)."
  ask_secret RENDER_DEPLOY_HOOK_URL "Paste the deploy hook URL:"
  write_env RENDER_DEPLOY_HOOK_URL "$RENDER_DEPLOY_HOOK_URL"
  set_secret RENDER_DEPLOY_HOOK_URL "$RENDER_DEPLOY_HOOK_URL"
  if (( ${#SKIPPED[@]} )) && [[ "${SKIPPED[${#SKIPPED[@]}-1]}" == *RENDER_DEPLOY_HOOK_URL* ]]; then
    note "Or on github.com: $REPO_SLUG → Settings → Secrets and variables → Actions →"
    note "New repository secret, name RENDER_DEPLOY_HOOK_URL."
  fi
  write_env RENDER_AUTO_DEPLOY hook
  SKIPPED+=("render.yaml: set autoDeployTrigger: off (and its pin in tests/test_deploy_config.py), then merge to master, so only CI's deploy-api job deploys")
  pause "Press Enter to continue"
}

stage_vercel_import() {
  stage "Vercel — import the window with Root Directory web"
  if [[ -n "$VERCEL_URL" ]] && check "the window loads at $VERCEL_URL" c_vercel_page; then
    ok "already deployed: nothing to do here"
    pause "Press Enter to continue"
    return
  fi
  open_url "https://vercel.com/new"
  step "Sign in (Continue with GitHub). Under Import Git Repository, click Import"
  step "next to financial-analyst-agent."
  note "Not listed? Use Adjust GitHub App Permissions (or Install) to give Vercel access."
  step "Project Name: financial-analyst-agent (your URL becomes <name>.vercel.app)."
  step "Root Directory: click Edit, pick web, click Continue. Framework Preset: Next.js."
  step "Leave Build and Output Settings and Environment Variables as they are: stage 6"
  step "sets the variables. Click Deploy and wait for the build (a few minutes)."
  pause "Press Enter once the deployment is Ready"
  step "Project → Settings → Domains: copy the <name>.vercel.app domain."
  note "Use that production domain, not a deployment URL (<name>-<hash>-<team>.vercel.app),"
  note "which Vercel puts behind a login. If the name was taken, Vercel added a suffix."
  ask_url VERCEL_URL "Paste the production URL:"
  write_env VERCEL_URL "$VERCEL_URL"
  until check "the window loads at $VERCEL_URL" c_vercel_page; do
    if ! confirm "Fix that, then check again?"; then
      SKIPPED+=("Vercel: the window did not load at $VERCEL_URL")
      return
    fi
  done
  pause "Press Enter to continue"
}

stage_vercel_env() {
  stage "Vercel — point the window at the API"
  if [[ -n "$VERCEL_URL" && -n "$RENDER_API_URL" ]]; then
    say "Checking whether the proxy already reaches the API…"
    # One quiet try first: before the variables are set, the proxy answers 502 at once.
    if healthy "$VERCEL_URL" && check_vercel; then
      ok "already set: nothing to do here"
      pause "Press Enter to continue"
      return
    fi
    note "Not yet. Set the variables:"
  fi
  open_url "https://vercel.com/dashboard"
  step "Open the project → Settings → Environment Variables. Add two variables, each"
  step "for Production and Preview (untick Development). Previews use the same API."
  note "If environments are a dropdown rather than checkboxes, choose them there."
  step "1. Key API_ORIGIN, value the Render URL (no trailing slash). Save."
  hand_over "API_ORIGIN" "$RENDER_API_URL"
  pause "Press Enter once API_ORIGIN is saved"
  step "2. Key API_PROXY_TOKEN, value the proxy token. Turn Sensitive on. Save."
  note "If you don't see a Sensitive switch by the value, look in the variable's ⋯ → Edit."
  hand_over "the proxy token" "$API_PROXY_TOKEN" secret
  pause "Press Enter once API_PROXY_TOKEN is saved"
  step "Variables reach new deployments only: Deployments → the latest Production"
  step "deployment → ⋯ → Redeploy → Redeploy. Wait until it is Ready."
  pause "Press Enter once the redeploy is Ready"
  until check_vercel; do
    if ! confirm "Fix that, then check again?"; then
      SKIPPED+=("Vercel variables (re-run scripts/deploy_wizard.sh --check once fixed)")
      return
    fi
  done
  pause "Press Enter to continue"
}

stage_proxy_check() {
  stage "Confirm the proxy is the only way in"
  say "The cutover checks: health through the Vercel URL, a guided story through the"
  say "proxy, and a refusal when anything calls Render without the token."
  FAILED=0
  check_render || true
  check_vercel || true
  while (( FAILED )); do
    note "Stage 3 covers Render and stage 6 covers Vercel; re-run the wizard to redo one."
    if ! confirm "Check again?"; then
      SKIPPED+=("proxy checks (scripts/deploy_wizard.sh --check)")
      return
    fi
    FAILED=0
    check_render || true
    check_vercel || true
  done
  pause "Press Enter to continue"
}

stage_browser_check() {
  stage "Browser check against the hosted window"
  say "Runs web/e2e against $VERCEL_URL: the four guided stories, compare-then-add-Apple,"
  say "the clarify round trip, and Start over. It takes a few minutes."
  local manual="browser check: cd web && PLAYWRIGHT_BASE_URL=$VERCEL_URL npm run test:e2e"
  if ! command -v npm >/dev/null 2>&1; then
    warn "npm not found: install Node 22, then run the browser check by hand"
    SKIPPED+=("$manual")
    pause "Press Enter to finish"
    return
  fi
  if [[ -n "$BROWSER_CHECK_PASSED" ]]; then ok "it passed on $BROWSER_CHECK_PASSED"; fi
  if ! confirm "Run it now?"; then
    if [[ -z "$BROWSER_CHECK_PASSED" ]]; then SKIPPED+=("$manual"); fi
    return
  fi
  if [[ ! -d web/node_modules ]]; then
    say "Installing the window's dependencies (npm ci)…"
    (cd web && npm ci) || { SKIPPED+=("$manual"); pause "npm ci failed. Press Enter to finish"; return; }
  fi
  say "Making sure Playwright's Chromium is installed…"
  if ! (cd web && npx playwright install chromium); then
    warn "Chromium did not install. On Linux or WSL: cd web && sudo npx playwright install-deps chromium"
  fi
  if (cd web && PLAYWRIGHT_BASE_URL="$VERCEL_URL" npm run test:e2e); then
    BROWSER_CHECK_PASSED=$(date -u +%Y-%m-%dT%H:%MZ)
    write_env BROWSER_CHECK_PASSED "$BROWSER_CHECK_PASSED"
    ok "the browser check passed against $VERCEL_URL"
  else
    warn "the browser check failed; the output above names the step."
    note "A first run after 15 idle minutes can time out while Render wakes: run it again."
    SKIPPED+=("$manual")
  fi
  pause "Press Enter to finish"
}

TOTAL_STAGES=8

banner "Go live: the window on Vercel, the API on Render"

stage_preflight
stage_token
stage_render
stage_autodeploy
stage_vercel_import
stage_vercel_env
stage_proxy_check
stage_browser_check

finish
say "Hosted window: ${VERCEL_URL:-not set}"
say "API:           ${RENDER_API_URL:-not set}"
say "Values:        $ENV_FILE (gitignored)"
note "Re-check any time: scripts/deploy_wizard.sh --check"
note "Ticket 11: record the hosted URL in its Answer."
printf '\n'
